BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "market_data" (
	"price"	REAL NOT NULL,
	"24h%"	REAL NOT NULL,
	"7d%"	REAL NOT NULL,
	"market_cap"	REAL NOT NULL COLLATE NOCASE,
	"volume_24h"	REAL NOT NULL,
	"supply"	REAL NOT NULL,
	"symbol"	TEXT NOT NULL,
	"timestamp"	NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "currencies" (
	"name"	TEXT NOT NULL UNIQUE,
	"symbol"	TEXT NOT NULL UNIQUE
);
COMMIT;
